version: '3'

services:
  api:
    container_name: wongames_api
    image: 081098/api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: 'sk_test_51JWqFBFXs0Qke4tjOFtCcaaYDGsF3kFuSJIneQP0ULlm7FQDbUgRPJDUGEtnsxuU6Jf173OVeI5VOEv8EPCB3uud005ppEjxJX'
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: 081098/database:latest
    ports:
      - '5432:5432'
